apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z79qs35qm-python
  janus-idp.io/tekton: z79qs35qm-python
  backstage.io/kubernetes-id: z79qs35qm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z79qs35qm-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
